---
services:
  api:
    build: ./api
    ports:
      - "80:9800"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"